# Generated by Django 4.2.5 on 2023-09-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_search', '0003_remove_location_description_remove_location_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('abbreviation', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='location',
            name='language_abbreviations',
        ),
        migrations.RemoveField(
            model_name='location',
            name='languages',
        ),
        migrations.AddField(
            model_name='location',
            name='languages',
            field=models.ManyToManyField(to='geo_search.language'),
        ),
    ]
