# Generated by Django 4.2.5 on 2023-09-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_search', '0004_language_remove_location_language_abbreviations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='language_abbreviations',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='location',
            name='languages',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.AddField(
            model_name='location',
            name='languages',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
