# Generated by Django 4.2.5 on 2023-09-18 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo_search', '0007_remove_location_languages_location_languages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='languages',
            new_name='language',
        ),
    ]
