# Generated by Django 4.2.5 on 2023-10-10 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo_search', '0011_country_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo_search.location'),
        ),
    ]
