# Generated by Django 4.2.5 on 2023-10-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_search', '0013_remove_country_location_location_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='country',
        ),
        migrations.AddField(
            model_name='country',
            name='locations',
            field=models.ManyToManyField(related_name='locations', to='geo_search.location'),
        ),
    ]
