# Generated by Django 4.2.5 on 2023-10-10 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo_search', '0015_remove_country_locations_location_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='name',
            new_name='names',
        ),
    ]
