# Generated by Django 4.2.5 on 2023-10-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_search', '0016_rename_name_country_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='names',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='location',
            name='country',
        ),
        migrations.AddField(
            model_name='country',
            name='locations',
            field=models.ManyToManyField(related_name='locations', to='geo_search.location'),
        ),
    ]
