# Generated by Django 5.0.3 on 2024-03-06 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo_search', '0018_remove_country_locations_location_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='country',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
