version: "3.8"

services:
  django:
    image: django
    container_name: django
    build: .
    ports:
      - 8000:8000
    expose:
      - "8000"
    volumes:
      - .:/myproject

    networks:
      - webnet

  nginx:
    build: ./nginx
    image: nginx:latest
    container_name: "nginx_con"
    depends_on:
      - django
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/static
      - ./media:/media

      - /etc/letsencrypt/live/geopositioning.uxlivinglab.online/fullchain.pem:/etc/letsencrypt/live/geopositioning.uxlivinglab.online/fullchain.pem:ro
      - /etc/letsencrypt/live/geopositioning.uxlivinglab.online/privkey.pem:/etc/letsencrypt/live/geopositioning.uxlivinglab.online/privkey.pem:ro
            
      
    ports:
      - "80:80"
      - 443:443
    networks:
      - webnet

  
  redis:
    image: redis:latest 
    container_name: redis
    networks:
      - webnet
    
networks:
  webnet:
    external: true

    
