version: "3.8"

services:
  django:
    image: django
    container_name: django
    build: .
    ports:
      - 8001:8000
    expose:
      - "8000"
    volumes:
      - .:/myproject
    networks:
      - webnet

  nginx:
    build: ./nginx
    image: nginx:latest
    container_name: "nginx_con"
    depends_on:
      - django
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/static
      - ./media:/media
      # - /home/dowell/100096-DowellChat-v2/nginx/certificate.crt:/home/dowell/100096-DowellChat-v2/nginx/certificate.crt:ro
      # - /home/dowell/100096-DowellChat-v2/nginx/private.key:/home/dowell/100096-DowellChat-v2/nginx/private.key:ro
      
      
    ports:
      - "80:80"
      - 443:443
    networks:
      - webnet

  
networks:
  webnet:
